version: 0.2

env:
  variables:
    IMAGE_REPO: "300615130618.dkr.ecr.ap-south-1.amazonaws.com/adrian"
    AWS_REGION: "ap-south-1"
    CLUSTER_NAME: "my-cluster"

phases:
  install:
    commands:
      - apt update -y
      - apt install docker.io -y
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $IMAGE_REPO"
      

  build:
    commands:
      - "docker build -t adrian ."
      - "docker tag adrian $IMAGE_REPO:$CODEBUILD_BUILD_NUMBER"

  post_build:
    commands:
      - "echo 'Pushing Docker image...'"
      - "docker push $IMAGE_REPO:$CODEBUILD_BUILD_NUMBER"
      - "echo 'Final deployment manifest:'"
      - "cat dist/manifest/deployment.yaml"
      - "aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME"