version: 0.2

env:
  variables:
    IMAGE_REPO: "300615130618.dkr.ecr.ap-south-1.amazonaws.com/adrian"
    
phases:
  install:
    commands:
      - apt update -y
      - apt install docker.io -y
      - |
        aws ecr get-login-password --region ap-south-1 \
        | docker login --username AWS --password-stdin $IMAGE_REPO

  build:
    commands:
      
      - docker build -t adrian .
      - docker tag adrian $IMAGE_REPO:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo "Pushing image to Amazon ECR..."
      - docker push $IMAGE_REPO:$CODEBUILD_BUILD_NUMBER
      - echo "Successfully pushed $IMAGE_REPO:$CODEBUILD_BUILD_NUMBER"
